name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Test security
        run: gosec ./...

      - name: Run tests
        run: go test ./...
      - name: Output coverage
        run: go test ./... -cover
  
  styling:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Install static checker
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check for formatting
        run: test -z $(go fmt ./...)

      - name: Check for linting
        run: staticcheck ./...
